# Generated by Django 5.2 on 2025-05-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
    ]
