# Generated by Django 5.2 on 2025-06-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20250516_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_code', models.CharField(max_length=20, unique=True)),
                ('material_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('base_unit', models.CharField(max_length=20)),
                ('material_group', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
