# Generated by Django 5.2 on 2025-06-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_material_delete_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('VARIANT', 'Variant Attribute'), ('GENERAL', 'General Attribute')], default='VARIANT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attributes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Barcode Image'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HSN Code'),
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='material',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GST %'),
        ),
        migrations.AddField(
            model_name='material',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit of Measurement'),
        ),
        migrations.AddField(
            model_name='material',
            name='vendor_article_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor Article Number'),
        ),
        migrations.AlterField(
            model_name='material',
            name='base_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, choices=[('ROH', 'Raw Material'), ('FERT', 'Finished Product'), ('HALB', 'Semi-Finished Product'), ('HAWA', 'Trading Goods'), ('VERP', 'Packaging Material'), ('DIEN', 'Service Material'), ('NLAG', 'Non-Stock Material'), ('ERSA', 'Spare Part'), ('LEER', 'Empties'), ('PIPE', 'Pipeline Material'), ('PROD', 'By-Product?')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_code', models.CharField(max_length=50, unique=True, verbose_name='Variant Code')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP')),
                ('sp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor_details', models.TextField(blank=True, null=True)),
                ('customer_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pages.material')),
            ],
            options={
                'db_table': 'material_variants',
                'ordering': ['variant_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialVariantAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.attribute')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='pages.materialvariant')),
            ],
            options={
                'db_table': 'material_variant_attribute_values',
                'ordering': ['attribute__name'],
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
