# Generated by Django 5.2 on 2025-08-29 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_attribute_material_barcode_image_material_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_code', models.CharField(max_length=20, unique=True, verbose_name='Channel Code')),
                ('channel_name', models.CharField(max_length=100, verbose_name='Channel Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['channel_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=20, unique=True, verbose_name='Category Code')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reporting_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=20, verbose_name='Category Code')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.channel')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pages.channelcategory')),
            ],
            options={
                'db_table': 'channel_categories',
                'ordering': ['channel__channel_name', 'category_name'],
                'unique_together': {('channel', 'category_code')},
            },
        ),
        migrations.CreateModel(
            name='MaterialChannelAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price')),
                ('channel_sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='Channel SKU')),
                ('channel_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Channel Product ID')),
                ('is_active', models.BooleanField(default=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission %')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shipping Cost')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_assignments', to='pages.channel')),
                ('channel_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_assignments', to='pages.channelcategory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_assignments', to='pages.material')),
                ('reporting_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_assignments', to='pages.reportingcategory')),
            ],
            options={
                'db_table': 'material_channel_assignments',
                'ordering': ['material__material_name', 'channel__channel_name'],
                'unique_together': {('material', 'channel')},
            },
        ),
    ]
