# Generated by Django 5.2 on 2025-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_channel_reportingcategory_channelcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
        migrations.AddField(
            model_name='channel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='channel_logos/', verbose_name='Channel Logo'),
        ),
    ]
