# Generated by Django 5.2.6 on 2025-10-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_channel_description_channel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked'),
        ),
        migrations.AddField(
            model_name='material',
            name='purchasing_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchasing Code'),
        ),
        migrations.AddField(
            model_name='material',
            name='variant_mandatory',
            field=models.BooleanField(default=False, verbose_name='Variant Mandatory'),
        ),
    ]
