# Generated by Django 5.2.6 on 2025-10-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_material_blocked_material_purchasing_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='material',
            name='purchasing_code',
        ),
        migrations.RemoveField(
            model_name='material',
            name='variant_mandatory',
        ),
    ]
