# Generated by Django 5.2.6 on 2025-10-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_material_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked'),
        ),
        migrations.AddField(
            model_name='material',
            name='purchasing_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchasing Code'),
        ),
        migrations.AddField(
            model_name='material',
            name='variant_mandatory',
            field=models.BooleanField(default=False, verbose_name='Variant Mandatory'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('pin_code', models.CharField(max_length=20, verbose_name='PIN Code')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['location_name'],
                'unique_together': {('location_name',)},
            },
        ),
    ]
