# Generated by Django 5.2.6 on 2025-10-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_material_blocked_material_purchasing_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('office', 'Office'), ('store', 'Store'), ('factory', 'Factory'), ('distribution_center', 'Distribution Center'), ('retail_outlet', 'Retail Outlet'), ('other', 'Other')], max_length=50, null=True, verbose_name='Location Type'),
        ),
    ]
