# Generated by Django 5.2.6 on 2025-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_location_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
        migrations.AddField(
            model_name='material',
            name='bom_excel_file',
            field=models.FileField(blank=True, null=True, upload_to='bom_excel/', verbose_name='BOM Excel File'),
        ),
    ]
