# Generated by Django 5.2 on 2026-06-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_add_bom_excel_file_to_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('APPROVED', 'APPROVED'), ('DOCUMENT_SUBMITTED', 'DOCUMENT_SUBMITTED'), ('UNDER_VERIFICATION', 'UNDER_VERIFICATION'), ('ACTIVE', 'ACTIVE'), ('REJECTED', 'REJECTED')], default='PENDING_APPROVAL', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('onboarding_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('msme_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='vendor_documents/gst/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='vendor_documents/pan/')),
                ('msme_certificate', models.FileField(blank=True, null=True, upload_to='vendor_documents/msme/')),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='vendor_documents/cheque/')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendor_registration',
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='bom_excel_file',
        ),
    ]
