# Generated by Django 5.2 on 2026-06-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_vendorregistration_remove_material_bom_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField()),
                ('supplier_email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('INVITED', 'INVITED'), ('USED', 'USED'), ('EXPIRED', 'EXPIRED')], default='INVITED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supplier_invitation',
            },
        ),
    ]
