# Generated by Django 5.2 on 2026-06-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_supplierinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorregistration',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.supplierinvitation'),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='status',
            field=models.CharField(choices=[('INVITED', 'INVITED'), ('REGISTRATION_SUBMITTED', 'REGISTRATION_SUBMITTED'), ('REGISTRATION_APPROVED', 'REGISTRATION_APPROVED'), ('DOCUMENTS_SUBMITTED', 'DOCUMENTS_SUBMITTED'), ('UNDER_VERIFICATION', 'UNDER_VERIFICATION'), ('ACTIVE', 'ACTIVE'), ('REJECTED', 'REJECTED'), ('CORRECTION_REQUIRED', 'CORRECTION_REQUIRED')], default='REGISTRATION_SUBMITTED', max_length=50),
        ),
    ]
