# Generated by Django 5.2 on 2026-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_vendorregistration_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorregistration',
            name='coi_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/coi/'),
        ),
    ]
