# Generated by Django 5.2 on 2026-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_vendorregistration_coi_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorregistration',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
