# Generated by Django 5.2 on 2026-06-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_vendorregistration_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('projects_count', models.IntegerField(default=0)),
                ('activities_count', models.IntegerField(default=0)),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'db_table': 'master_department',
            },
        ),
    ]
