# Generated by Django 5.2 on 2026-07-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=20)),
                ('project_code', models.CharField(max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wbs', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=15, null=True)),
                ('apr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('may', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('jun', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('jul', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('aug', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sep', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('oct', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nov', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dec', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('jan', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('feb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mar', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.department')),
            ],
            options={
                'db_table': 'budget_allocation',
            },
        ),
    ]
